### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by jmrchelani** [NeatCoders/bolt-point-of-sale#1]
- [ ] Add basic layout
- [x] Add a list of things to be implemented
- [ ] Add functionality readmes for ease of coding contributors
- [x] Add separate issues for all remaining things to be implemented and assign tasks

- [x] Add a New Sale window
- [x] Add sales history window
- [x] Add "ADD a new Item" window
- [x] Add "Remove an item" window

- [ ] Add Database Connectivity
- [ ] Create Database

- [ ] Add all functionality

- [ ] Release v1

- [ ] Fix bugs if any

- [ ] Further updates - color etc

- [ ] Add Documentation

**Comment by jmrchelani** [comment]
@all-contributors add @jmrchelani for code

**Comment by KumarKelashMeghwar** [comment]
#11  #19  done!

**Comment by jmrchelani** [comment]
Noted
